---

- hosts: localhost
  connection: local
  run_once: true
  become: true
  environment:
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
  tasks:
  - import_role:
      name: ansible
