---

- name: Install packages
  apt:
    pkg:
    - snapd
    - vim
    - curl
    - wget
    - jq
    - git

- name: Install snaps
  snap:
    name: "{{ item.name }}"
    classic: "{{ item.classic }}"
    channel: "{{ item.channel }}"
  with_items:
  - name: code
    classic: true
    channel: stable
  - name: helm
    classic: true
    channel: stable

